### ISSUE TITLE
架构图讨论

### ISSUE THREAD

**Issue by Silverster98** [Silverster98/bitmips2019#1]
### 基本能看懂，但是个别信号还有有点疑问
- exe_aluop_i 信号，exe_regfile_write_addr_i 信号。这两信号是从exe级来的吗？具体作用还是不太懂。
- mem_to_reg_o是一个控制信号吗？（控制写回级写入寄存器堆的数据来自哪）
- id_stall_request 是load指令对应的阻塞请求吗
- 那个pc_return_addr也需要往后面流水吧，他不是也要回写到regfile吗？但你的id/exe模块没有这个入口

**Comment by moon548834** [comment]
1. 是的 exe_aluop_i 信号，exe_regfile_write_addr_i 是来解决旁路相关的，但是我觉得也可以不用这个信号，可以被替换。就比如你想判断旁路阻塞，这个时候你在id级有个指令是lw，你要看lw的寄存器内容是否被上一条指令(也就是目前在exe级的)的更改了，所以我们需要根据exe的一些信息写回到id，用来解决lw的阻塞问题
2. mem_to_reg 可以先不实现，用你的选择器。这个信号本意是产生一个信号，判断WB的时候写入数据是来自alu的结果还是ram的
3. 是的
4. 这个我是参考《手把手》加的，就是有些跳转指令有一个返回地址，(我还没实现，不知道你清不清楚)它应该不需要往后流水 。

**Comment by moon548834** [comment]
问题 1. hilo_read_addr 你是通过 1‘b0 或者 1'b1 来判断是hi和lo吗

**Comment by Silverster98** [comment]
之前没实现HILO，但是初步我觉得可以这样设计

**Comment by Silverster98** [comment]
我发现id级没有imm16信号，然后我加了，我这样想，imm16信号送到id/ex模块，然后在id/ex模块产生sign_extend_imm16,zero_extend_imm16和load_upper_imm16这三个信号

**Comment by moon548834** [comment]
1 如果cp0(regfile hilo 同)是组合逻辑，也就是没有clk的话，那么就可以认为是实时更新的，对于cp0来说，在mem级判断是否有中断需要cp0_cause和cp0_status(这两个就够了)的信息，但是此时wb级可能有一条往cp0_status写的信息，可能是指令：MTC0。 那么对于组合逻辑而言，wb级写入cp0_status新的数值，在mem级中我们理论上可以读到这个正确的值。 如果对于cp0是时序电路而言，我们在mem级中读到的是旧值，所以如果是时序的话，应该还要一个旁路。 
PS:我记得你说过你用下降沿来判断，但是前半个周期相当于mem读到的还是旧值，后半个周期会读到新值，理论上似乎可以，但可能频率高会不满足保持时间？？  待商讨
2. 在MEM/WB的时候 有ram_data和alu_data 最后往regfile里面写的数值根据mem_to_reg来判断，这个判断放到WB？ 
3. ram_read_addr这个信号理论上ID级就可以产生了，但我们好像忽略了它，还是等到EXE再产生？

**Comment by Silverster98** [comment]
1. cp0那一块就是用组合逻辑是不是会产生回路？MEM级需要status,然后cp0也会写status
2. 我觉得可以直接放到 MEM/WB里面，这样WB就不用写了
3. ram_read_addr这个信号不是需要exe的参与吗，他是base+offset,就是跟ram_write_addr是一样的

**Comment by moon548834** [comment]
1. 但听起来 cp0的status会更新到mem读到的status上的，毕竟你只是个组合
2. 好
3. 嗯 那就exe产生
好像没啥问题了(有问题再说) 你之前说的咋提交，就是说明文件组织啥的

**Comment by moon548834** [comment]
git我大概懂了 然后就是每次提交.xpr 应该是不行的吧(如果有ip核，和.v文件)，应该是整个文件夹都要提交..?
我晚上先写个pc 然后你这两天你写id的一点？，就是代表性的几条，然后我看看，扩展我来做，我应该能看懂。

**Comment by Silverster98** [comment]
你在vivado里面创建文件，他会生成到bitmips.src这个文件夹下，我们写的代码都在这个文件夹下，所以只保留这个就可以了

**Comment by moon548834** [comment]
我的id还有些没加，里面的格式我一会再改..
晚上把regfile 和 hilo cp0加上..

**Comment by moon548834** [comment]
说明 
1. regfile的旁路我移到了id阶段，因为比如一个beq的判断，根据rs和rt判断是否跳转，但是rs,rt可能会被再ex,mem,wb的写指令修改，所以，寄存器堆的旁路必须在id 就已经完善了(因为我们把分支跳转移到了ID级)。 另外由于bypass_wb 实际上就是要写回的信号，故我只定义了 bypass_ex 和 bypass_mem。我一会改一下process on，更清楚一点。
2. 感觉CP0很复杂实际上，我看了学长那个，感觉还是需要把CP0详细一点..就是我们目前实现哪些？那个sel咋搞... 感觉需要统一一下
3. 你来写MEM吗，还是CP0？
4. 还有个问题 我看你process on 里面的 ID/EX 和 EX 最后有4个信号 rs,rt,hilo,cp0的读地址信号，为啥要有这个..难道不应该在ID都读出了他们对应的数据了吗？

**Comment by Silverster98** [comment]
1.ok
2.cp0确实还是有点复杂，昨天我跟学长也讨论了一下。再说吧。。。sel是哪个sel?
3.我来写mem吧
4.这个是判断数据冲突的啊。。之前我还问过你。。

**Comment by Silverster98** [comment]
1.cp0那一块，如果是普通的MTC0这种指令写，那么就是可以是跟regfile一样写，但是如果是由于异常导致写cp0，那么需要是有时序的，貌似只能在下降沿写
2.还有就是RAM的问题，那个还需要对字节选择

**Comment by moon548834** [comment]
上上条4点 ok明白了
这条
1. 不太懂 ，因为我看《手把手》里面MTC0和异常两种方式都是上升沿..
2. RAM的你可以EXE的时候判断，你自己加个信号，判断是字节还是啥的，或者你想id判断也行，告诉我接口格式？

**Comment by moon548834** [comment]
对了 我那个ALUOP改成八位的了 就是无脑映射了 当然指令还不全 你可以再加.. 因为仅根据OP位判断不了，所以我在defins.v里面定义的就是从0000_0000开始(就没有说明实际意义，只是个映射方式)，你可以随便改，只要保证不重复就行。

**Comment by moon548834** [comment]
ID现在只差乘除法和cp0的了，我明天把cp0写一个简单的。(ID我还需要再修改一下，和你的接口兼容)
你这个ex_load_upper_imm16是啥，前两个我知道是符号拓展，0拓展，(我应该还需要一个，高16位保持imm,低16位0拓展,这个信号是指这个吗)

**Comment by moon548834** [comment]
打算就写一个类似于学长cp0的.. 先写个基础版的，之后再改..  这个时候mem（判断int）就不需要cause,status判断了，直接都送到cp0，让cp0去判断是不是中断，我看学长代码就是这样。你先写着exe，mfc0和mtc0的判断先留下，我来写。

**Comment by moon548834** [comment]
CP0协处理我打算先用学长的..然后我TLB先不管，或者注释掉。信号的话，也是兼容学长那个CP0的。当然信号产生的具体实现不一样，这个我写。 因为我觉得CP0是个大坑，能别造轮子就先别造了，感觉和性能可能也没太大关系.. 有这个功能就行， 学长那个带TLB的写了1k行..

**Comment by moon548834** [comment]
我在process on里面定义了那个exception_type的格式，今天我改了一点，就是ram的地址错误，lw类的和sw类的要不同才可以。因为cp0处理他们的code不一样。具体参照 MIPS32_microMIPS32_Privileged_Resource_Architecture.pdf 这个里面 212页。
