### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Silverster98** [Silverster98/bitmips2019#2]
1. id模块输出的cp0_read_addr_o是xx
2. cp0模块的flush_o是x
3. 一旦出现一个延时槽后，id模块的now_in_delayslot和next_in_delayslot就一直是1
4. id模块160行，不应该先判断 funct,根据funct来判断指令类型么？你是先判断的shamt,这样的话你这样0x00000c00指令就会写reg[1],这条应该是nop
5. 还是id 模块问题，I型指令根据op判断，你有一些还是放在 op=0的判断里了。

**Comment by moon548834** [comment]
1. 已修复
2. 已修复
3. 已修复
4. 我把shamt注释了 只有0x0000_0000才是nop 严格按照定义来的话..  其实有个问题，就是有些指令就是仅仅依据一个op或者 funct 只是一个必要条件， 按照手册上给的，同时还必须确保某些位一定是0.. 这个我没有严格按照手册实现，因为我看学长他们和手把手的都是不很严格..
5. 现在应该都改好了..但是我systhesis的时候 有个warning是说 case(op) 里面6'b001000 unreachable 很迷，没太懂。

我看了下仿真波形 应该是这几条没什么问题了。

**Comment by Silverster98** [comment]
1. regfile 当读取内容时不能用时序逻辑，需要组合逻辑，给出地址，立即给出数据，你在上升沿给出数据是上一个周期指令要的数据。
2. id模块569~581行的两个指令重复，我给注释了

注：我重新写入了一个测试程序，是一个简单的斐波拉契数列计算，你可以直接跑

代码：
```
    .org 0x0
    .set noat
    .data  
    .text
main:
    addiu $t0, $0, 6
    addiu $t1, $0, 1
    addiu $t2, $0, 1
    j loop
    addiu $t4, $0, 15
    addiu $t5, $0, 15
loop:
    add   $t3, $t1, $t2
    ori   $t1, $t2, 0
    ori   $t2, $t3, 0
    addiu $t0, $t0, -1
    bgtz  $t0, loop
    addiu $t4, $0, 15
loop2:
    bgtz  $t4, loop2
    

```

**Comment by moon548834** [comment]
1. 已修改
2. 已删除
3. 运行结果应该是正确的，如果我没理解错的话。 六个周期斐波那契 然后一直loop2循环。

**Comment by Silverster98** [comment]
关于hilo cp0数据冲突bug
```
|    mult      |               |               |               |                       |
|               |             |             |             |                      |
|               |             |             |             |                      |
|               |             |             |   mfhi   |                      |
|               |             |             |             | mfhi读hi为0  |
|               |             |             |             |                      | mfhi无法通过旁路解决  |                  |
|               |             |             |             |                      |

```

就是在特殊周期出现时，对于cp0和hilo的数据冲突无法解决。

解决方案：
- （1）在ex级再加旁路，读取hilo,cp0解决
- （2）hilo,cp0取数放到id,id级处理冲突

**Comment by Silverster98** [comment]
另：id模块貌似bug还挺多，我看到一些aluop的赋值都是错的，我给改了。id模块写的比较混乱，考虑一下重新组织一下代码并检测一下bug

**Comment by Silverster98** [comment]
1. id模块修改：syscall和break,eret，这三条指令也是例外，在id级即可确定，你直接在id级写到exception_type里。然后到cp0判断跳转。
2. cp0的cp0_return_pc问题，当异常是eret时，cp0_return_pc是cp0_epc的值，对于其他异常，指令要跳转到0xBFC0.0380 （文档A03 5.1.2），但是我们早期实验没有这个地址，所以先跳到0x00000020(自己动手写的这个)。

**Comment by moon548834** [comment]
eret现在没问题了，原因是exception_type在ex级传递有点问题，我改了下你的ex，你可以看看patch，不多就四五行，你可以根据我的再按你的习惯改一下。
至少现在eret可以了，跳转正在测。

**Comment by moon548834** [comment]
提交了几次，ID和cp0不完善的地方我又改了下。然后顶层有一个stall的bug 就是id(lw)和exe(div)都会请求stall，但是在pc if_id那块原来你没有 把它俩或起来，其他都ok。

**Comment by moon548834** [comment]
你写的定时器中断测试完成，没有问题了，我上传的inst.coe 是改过j指令的，可以直接用。

**Comment by moon548834** [comment]
最新的submit 我改了两处bug 你看下Patch就好。
然后现在新的问题是 取指令那块 可能会有一条指令被忽略掉，你可以看波形。
我改了一版，可以跑到11W纳秒，但是还是INSTR相关的错，所以没push,你可以看看pc那块..感觉不太好改。就是从ROM读的INSTR，在这个周期，可能已经被stall了，但是我们没法stall这个ROM，因为在延时中，所以指令会被覆盖掉。

**Comment by Silverster98** [comment]
修改方案：
1. 总共4个stall信号：inst_stall id_stall_request exe_stall data_stall, 把这个四个stall信号构成一个四位信号，然后传给各级。依据stall来修改。
2. 现在的问题就是，branch指令处于id级时，延时槽处于if,id在头一个周期就会生成跳转信号，导致延时槽指令还没取出。这就需要branch指令保持到if的第二个周期再起作用。
